local default_options = {
  keys = {
    --  current_speech = "<leader>hc",
    --  update_linenr = "<leader>hu",
    --  update_timestamp = "<leader>hU",
    --  previous_speech = "<leader>hp",
    --  next_speech ="<leader>hn",
    --  goto_speech = "<leader>hg"
    --  goto_timestamp = "<leader>ht"
    --  merge_lines = "M",
    --  slice_to_line_above = "<leader>hs",
    --  slice_to_line_below = "<leader>hS",
    --  remove_slice = "<leader>hd",
    --  replace_symbols = "<leader>hr"
    --  convert_textmode = "<leader>hT"
    --  remove_words = "<leader>hR",
    --  execute_line = "<leader>he",
    --  open_link = "<leader>hl",
    --  update_pdf = "<leader>hz",
    --  generate_pdf_and_open = "<leader>hZ",
    -- convert_line_to_node = "<leader>hM",
    -- bolden_timestamped_line = "<leader>hb",
    -- box_line_primary = "<leader>hBl",
    -- box_block_primary = "<leader>hBb",
    -- box_line_secondary = "<leader>hBL",
    -- box_block_secondary = "<leader>hBB",
    -- box_set_comment = "<leader>hBs",
    -- convert_lines_to_nodes = "<leader>hN",
    -- remove_disturbing_prefix = "<leader>hC",
  },
  box = {
    comment = "# ",
    width = 79,
    padding = 1,
    chars = {
      primary = "-",
      secondary = "=",
    },
  },
  replace_symbols = {
    ["⊔"] = "\\sqcup",
    ["⊑"] = "\\sqsubseteq",
    ["⊆"] = "\\subseteq",
    ["⊒"] = "\\sqsupseteq",
    ["̸="] = "\\ne",
    ["≤"] = "\\leq",
    ["≥"] = "\\geq",
    ["¬"] = "\\neg",
    ["∨"] = "\\lor",
    ["∧"] = "\\land",
    ["Σ"] = "\\sum",
    ["∩"] = "\\cap",
    ["∪"] = "\\cup",
    ["�→"] = "\\mapsto",
    ["→"] = "\\rightarrow",
    ["↔"] = "\\Leftrightarrow",
    ["∆"] = "\\Delta",
    ["⊨"] = "\\models",
    ["∈"] = "\\in",
    ["·"] = "\\cdot",
    ["◦"] = "\\circ",
    ["∀"] = "\\forall",
    ["∃"] = "\\exits",
    ["ε"] = "\\epsilon",
    ["α"] = "\\alpha",
    ["β"] = "\\beta",
    ["γ"] = "\\gamma",
    ["ℓ"] = "\\ell",
    ["π"] = "\\pi",
    ["ψ"] = "\\psi",
    ["σ"] = "\\sigma",
    ["τ"] = "\\tau",
    ["λ"] = "\\lambda",
    ["#"] = "^\\#",
    ["⊤"] = "\\top",
    ["⊥"] = "\\bot",
    ["▽"] = "\\triangledown",
    ["◁"] = "\\triangleleft",
    ["∅"] = "\\emptyset",
    ["{"] = "\\{",
    ["}"] = "\\}",
    ["∞"] = "\\infty",
    [" %. %. %. "] = "\\ldots",
    ["▶"] = "\\item",
    ["1%."] = "\\item",
    ["2%."] = "\\item",
    ["3%."] = "\\item",
    ["4%."] = "\\item",
  },
  prefix = "", -- "- "
  unneeded_words = {
    "uh",
    "oh",
    "um",
    "yeah",
    "sorry",
    "well",
  },
  -- playerctl_position_workaround = true,
  -- lowercase_inserted_lines = true,
}

return default_options
