local default_options = {
  -- keys = {
  --  current_speech = "<leader>hc",
  --  previous_speech = "<leader>hp",
  --  next_speech ="<leader>hn",
  --  goto_speech = "<leader>hg"
  --  replace_symbols = "<leader>hr"
  -- },
  symbols = {
   ["⊔"] = "\\sqcup",
   ["⊑"] = "\\sqsubseteq",
   ["⊆"] = "\\subseteq",
   ["⊒"] = "\\sqsupseteq",
   ["̸="] = "\\ne",
   ["≤"] = "\\leq",
   ["≥"] = "\\geq",
   ["¬"] = "\\neg",
   ["∨"] = "\\lor",
   ["∧"] = "\\land",
   ["Σ"] = "\\sum",
   ["∩"] = "\\cap",
   ["∪"] = "\\cup",
   ["�→"] = "\\mapsto",
   ["→"] = "\\rightarrow",
   ["↔"] = "\\Leftrightarrow",
   ["∆"] = "\\Delta",
   ["⊨"] = "\\models",
   ["∈"] = "\\in",
   ["·"] = "\\cdot",
   ["◦"] = "\\circ",
   ["∀"] = "\\forall",
   ["∃"] = "\\exits",
   ["ε"] = "\\epsilon",
   ["α"] = "\\alpha",
   ["β"] = "\\beta",
   ["γ"] = "\\gamma",
   ["ℓ"] = "\\ell",
   ["π"] = "\\pi",
   ["ψ"] = "\\psi",
   ["σ"] = "\\sigma",
   ["τ"] = "\\tau",
   ["λ"] = "\\lambda",
   ["#"] = "^\\#",
   ["⊤"] = "\\top",
   ["⊥"] = "\\bot",
   ["▽"] = "\\triangledown",
   ["◁"] = "\\triangleleft",
   ["∅"] = "\\emptyset",
   ["{"] = "\\{",
   ["}"] = "\\}",
   ["∞"] = "\\infty"
  },
  prefix = "" -- "- "
}

return default_options
